// Realistic editorial images can be added one palette at a time.
// Palettes without an entry continue to use the scalable SVG figures.
export const LOOKS = {
  1: {
    pair: "/looks/plate-001.jpg",
    alt: "Two models wearing the Cerulian Blue and English Red combination",
  },
  2: {
    pair: "/looks/plate-002.jpg",
    alt: "Two models wearing the Dark Tyrian Blue and Yellow Orange combination",
  },
  3: {
    pair: "/looks/plate-003.jpg",
    alt: "Two models wearing the Raw Sienna and Pale Lemon Yellow combination",
  },
  4: {
    pair: "/looks/plate-004.jpg",
    alt: "Two models wearing the Red Violet and Isabella Color combination",
  },
  5: {
    pair: "/looks/plate-005.jpg",
    alt: "Two models wearing the Vandar Poel's Blue and Cossack Green combination",
  },
  6: {
    pair: "/looks/plate-006.jpg",
    alt: "Two models wearing the Deep Indigo and Grenadine Pink combination",
  },
  7: {
    pair: "/looks/plate-007.jpg",
    alt: "Two models wearing the Orange and Glaucous Green combination",
  },
  8: {
    pair: "/looks/plate-008.jpg",
    alt: "Two models wearing the Cinnamon Rufous and Grayish Lavender combination",
  },
  9: {
    pair: "/looks/plate-009.jpg",
    alt: "Two models wearing the Violet Red and Dull Blue Violet combination",
  },
  10: {
    pair: "/looks/plate-010.jpg",
    alt: "Two models wearing the Dark Citrine and Cinnamon Rufous combination",
  },
  11: {
    pair: "/looks/plate-011.jpg",
    alt: "Two models wearing the Mineral Gray and Ivory Buff combination",
  },
  12: {
    pair: "/looks/plate-012.jpg",
    alt: "Two models wearing the Green Blue and Isabella Color combination",
  },
  13: {
    pair: "/looks/plate-013.jpg",
    alt: "Two models wearing the Veronia Purple and Raw Sienna combination",
  },
  14: {
    pair: "/looks/plate-014.jpg",
    alt: "Two models wearing the Spinel Red and Naples Yellow combination",
  },
  15: {
    pair: "/looks/plate-015.jpg",
    alt: "Two models wearing the Benzol Green and Grayish Lavender combination",
  },
  16: {
    pair: "/looks/plate-016.jpg",
    alt: "Two models wearing the Vandyke Red and Pale King's Blue combination",
  },
  17: {
    pair: "/looks/plate-017.jpg",
    alt: "Two models wearing the Eugenia Red and Sea Green combination",
  },
  18: {
    pair: "/looks/plate-018.jpg",
    alt: "Two models wearing the Dusky Madder Violet and Fawn combination",
  },
  19: {
    pair: "/looks/plate-019.jpg",
    alt: "Two models wearing the Mars Brown Tobacco and Night Green combination",
  },
  20: {
    pair: "/looks/plate-020.jpg",
    alt: "Two models wearing the Laelia Pink and Calamine Blue combination",
  },
  21: {
    pair: "/looks/plate-021.jpg",
    alt: "Two models wearing the Sea Green and Grenadine Pink combination",
  },
  22: {
    pair: "/looks/plate-022.jpg",
    alt: "Two models wearing the Deep Lyons Blue and Yellow combination",
  },
  23: {
    pair: "/looks/plate-023.jpg",
    alt: "Two models wearing the Light Mauve and Cinnamon Buff combination",
  },
  24: {
    pair: "/looks/plate-024.jpg",
    alt: "Two models wearing the Sepia and Veronia Purple combination",
  },
  25: { pair: "/looks/plate-025.jpg", alt: "Two models wearing the Etruscan Red and Nile Blue combination" },
  26: { pair: "/looks/plate-026.jpg", alt: "Two models wearing the Pale Raw Umber and Golden Yellow combination" },
  27: { pair: "/looks/plate-027.jpg", alt: "Two models wearing the Slate Color and Corinthian Pink combination" },
  28: { pair: "/looks/plate-028.jpg", alt: "Two models wearing the Deep Indigo and Madder Brown combination" },
  29: { pair: "/looks/plate-029.jpg", alt: "Two models wearing the Krongbergs Green and Salvia Blue combination" },
  30: { pair: "/looks/plate-030.jpg", alt: "Two models wearing the Pompeian Red and Mineral Gray combination" },
  31: {
    pair: "/looks/plate-031.jpg",
    alt: "Two models wearing the Red Orange and Pale Lemon Yellow combination",
  },
  32: {
    pair: "/looks/plate-032.jpg",
    alt: "Two models wearing the Ochraceous Salmon and Night Green combination",
  },
  33: { pair: "/looks/plate-033.jpg", alt: "Two models wearing the Slate Color and Raw Sienna combination" },
  34: { pair: "/looks/plate-034.jpg", alt: "Two models wearing the Eosine Pink and Neutral Gray combination" },
  35: { pair: "/looks/plate-035.jpg", alt: "Two models wearing the Carmine Red and Light Brown Drab combination" },
  36: {
    pair: "/looks/plate-036.jpg",
    alt: "Two models wearing the Sulphine Yellow and Turquoise Green combination",
  },
  37: { pair: "/looks/plate-037.jpg", alt: "Two models wearing the Red Violet and Brick Red combination" },
  38: { pair: "/looks/plate-038.jpg", alt: "Two models wearing the Deep Lyons Blue and Diamine Green combination" },
  39: { pair: "/looks/plate-039.jpg", alt: "Two models wearing the Helvetia Blue and Carmine combination" },
  40: {
    pair: "/looks/plate-040.jpg",
    alt: "Two models wearing the Vinaceous Tawny and Citron Yellow combination",
  },
  41: { pair: "/looks/plate-041.jpg", alt: "Two models wearing the Dark Citrine and Calamine Blue combination" },
  42: { pair: "/looks/plate-042.jpg", alt: "Two models wearing the Violet and Yellow Ocher combination" },
  43: { pair: "/looks/plate-043.jpg", alt: "Two models wearing the Aconite Violet and Corinthian Pink combination" },
  44: { pair: "/looks/plate-044.jpg", alt: "Two models wearing the Olympic Blue and Light Porcelain Green combination" },
  45: {
    pair: "/looks/plate-045.jpg",
    alt: "Two models wearing the Seashell Pink and Lemon Yellow combination",
  },
  46: { pair: "/looks/plate-046.jpg", alt: "Two models wearing the Black and Orange combination" },
  47: { pair: "/looks/plate-047.jpg", alt: "Two models wearing the Etruscan Red and Grayish Lavender B combination" },
  48: { pair: "/looks/plate-048.jpg", alt: "Two models wearing the Helvetia Blue and Rosolanc Purple combination" },
  49: { pair: "/looks/plate-049.jpg", alt: "Two models wearing the Blue and Pale King's Blue combination" },
  50: { pair: "/looks/plate-050.jpg", alt: "Two models wearing the Dusky Madder Violet and Ivory Buff combination" },
  51: { pair: "/looks/plate-051.jpg", alt: "Two models wearing the Carmine Red and Blue combination" },
  52: { pair: "/looks/plate-052.jpg", alt: "Two models wearing the Black and Sulpher Yellow combination" },
  53: { pair: "/looks/plate-053.jpg", alt: "Two models wearing the Dusky Madder Violet and Yellow Orange combination" },
  54: { pair: "/looks/plate-054.jpg", alt: "Two models wearing the Benzol Green and Light Glaucous Blue combination" },
  55: { pair: "/looks/plate-055.jpg", alt: "Two models wearing the Old Rose and White combination" },
  56: { pair: "/looks/plate-056.jpg", alt: "Two models wearing the Violet and Grayish Lavender B combination" },
  57: { pair: "/looks/plate-057.jpg", alt: "Two models wearing the Slate Color and Taupe Brown combination" },
  58: { pair: "/looks/plate-058.jpg", alt: "Two models wearing the Hay's Russet and Sea Green combination" },
  60: { pair: "/looks/plate-060.jpg", alt: "Two models wearing the Dark Tyrian Blue and Pale Lemon Yellow combination" },
  61: { pair: "/looks/plate-061.jpg", alt: "Two models wearing the Cotinga Purple and Light Green Yellow combination" },
  62: { pair: "/looks/plate-062.jpg", alt: "Two models wearing the Black and Yellow combination" },
  63: { pair: "/looks/plate-063.jpg", alt: "Two models wearing the Vistoris Lake and Cerulian Blue combination" },
  64: { pair: "/looks/plate-064.jpg", alt: "Two models wearing the Dark Soft Violet and Aconite Violet combination" },
  67: { pair: "/looks/plate-067.jpg", alt: "Two models wearing the Dark Tyrian Blue and Olympic Blue combination" },
  69: { pair: "/looks/plate-069.jpg", alt: "Two models wearing the Black and Warm Gray combination" },
  70: { pair: "/looks/plate-070.jpg", alt: "Two models wearing the Lincoln Green and Raw Sienna combination" },
  71: { pair: "/looks/plate-071.jpg", alt: "Two models wearing the Pompeian Red and Ochraceous Salmon combination" },
  72: { pair: "/looks/plate-072.jpg", alt: "Two models wearing the Pale King's Blue and Sulpher Yellow combination" },
  73: { pair: "/looks/plate-073.jpg", alt: "Two models wearing the Pale Raw Umber and Rainette Green combination" },
  74: { pair: "/looks/plate-074.jpg", alt: "Two models wearing the Green Blue and Turquoise Green combination" },
  75: { pair: "/looks/plate-075.jpg", alt: "Two models wearing the Violet Blue and Pale King's Blue combination" },
  77: { pair: "/looks/plate-077.jpg", alt: "Two models wearing the Vandar Poel's Blue and Eugenia Red B combination" },
  78: { pair: "/looks/plate-078.jpg", alt: "Two models wearing the Venice Green and Pinkish Cinnamon combination" },
  79: { pair: "/looks/plate-079.jpg", alt: "Two models wearing the Madder Brown and Green Blue combination" },
  80: { pair: "/looks/plate-080.jpg", alt: "Two models wearing the Light Mauve and Sulpher Yellow combination" },
  82: { pair: "/looks/plate-082.jpg", alt: "Two models wearing the Dusky Madder Violet and Hay's Russet combination" },
  83: { pair: "/looks/plate-083.jpg", alt: "Two models wearing the Violet Blue and Olive Buff combination" },
  59: {
    pair: "/looks/plate-059.jpg",
    alt: "Two models wearing the Citrine and Eosine Pink combination",
  },
  65: {
    pair: "/looks/plate-065.jpg",
    alt: "Two models wearing the Sulphine Yellow and Calamine Blue combination",
  },
  66: {
    pair: "/looks/plate-066.jpg",
    alt: "Two models wearing the Olive Green and Olive Ocher combination",
  },
  68: {
    pair: "/looks/plate-068.jpg",
    alt: "Two models wearing the Light Brown Drab and Yellow combination",
  },
  76: {
    pair: "/looks/plate-076.jpg",
    alt: "Two models wearing the Warm Gray and Pale Lemon Yellow combination",
  },
  81: {
    pair: "/looks/plate-081.jpg",
    alt: "Two models wearing the Warm Gray and Golden Yellow combination",
  },
  86: {
    pair: "/looks/plate-086.jpg",
    alt: "Two models wearing the Raw Sienna and Sea Green combination",
  },
  87: {
    pair: "/looks/plate-087.jpg",
    alt: "Two models wearing the Citron Yellow and Corinthian Pink combination",
  },
  93: {
    pair: "/looks/plate-093.jpg",
    alt: "Two models wearing the Citrine and Light Glaucous Blue combination",
  },
  96: {
    pair: "/looks/plate-096.jpg",
    alt: "Two models wearing the Olive and Yellow Ocher combination",
  },
  97: {
    pair: "/looks/plate-097.jpg",
    alt: "Two models wearing the Etruscan Red and Corinthian Pink combination",
  },
  102: {
    pair: "/looks/plate-102.jpg",
    alt: "Two models wearing the Orange Rufous and Ivory Buff combination",
  },
  104: {
    pair: "/looks/plate-104.jpg",
    alt: "Two models wearing the Carmine Red and Sulpher Yellow combination",
  },
  107: {
    pair: "/looks/plate-107.jpg",
    alt: "Two models wearing the Light Grayish Olive and Apricot Yellow combination",
  },
  109: {
    pair: "/looks/plate-109.jpg",
    alt: "Two models wearing the Blackish Olive and Pale Lemon Yellow combination",
  },
  222: {
    pair: "/looks/plate-222.jpg",
    alt: "Two models wearing the Orange Rufous and Yellow Ocher combination",
  },
  84: { pair: "/looks/plate-084.jpg", alt: "Two models wearing the Deep Slate Green and Seashell Pink combination" },
  85: { pair: "/looks/plate-085.jpg", alt: "Two models wearing the Antwarp Blue and Vinaceous Tawny combination" },
  88: { pair: "/looks/plate-088.jpg", alt: "Two models wearing the Blue and Seashell Pink combination" },
  89: { pair: "/looks/plate-089.jpg", alt: "Two models wearing the Violet Blue and Yellow Orange combination" },
  90: { pair: "/looks/plate-090.jpg", alt: "Two models wearing the Aconite Violet and Eosine Pink combination" },
  91: { pair: "/looks/plate-091.jpg", alt: "Two models wearing the Vistoris Lake and Orange Rufous combination" },
  92: { pair: "/looks/plate-092.jpg", alt: "Two models wearing the Benzol Green and Coral Red combination" },
  94: { pair: "/looks/plate-094.jpg", alt: "Two models wearing the Dusky Green and Ivory Buff combination" },
  95: { pair: "/looks/plate-095.jpg", alt: "Two models wearing the Dull Violet Black and Hay's Russet combination" },
  98: { pair: "/looks/plate-098.jpg", alt: "Two models wearing the Madder Brown and Violet Blue combination" },
  99: { pair: "/looks/plate-099.jpg", alt: "Two models wearing the Cerulian Blue and Pale Lemon Yellow combination" },
  100: { pair: "/looks/plate-100.jpg", alt: "Two models wearing the Dull Blue Violet and Buffy Citrine combination" },
  101: { pair: "/looks/plate-101.jpg", alt: "Two models wearing the Deep Lyons Blue and Cameo Pink combination" },
  103: { pair: "/looks/plate-103.jpg", alt: "Two models wearing the Dusky Madder Violet and Cinnamon Rufous combination" },
  105: { pair: "/looks/plate-105.jpg", alt: "Two models wearing the Chromium Green and Cameo Pink combination" },
  106: { pair: "/looks/plate-106.jpg", alt: "Two models wearing the Dull Violet Black and Antwarp Blue combination" },
  108: { pair: "/looks/plate-108.jpg", alt: "Two models wearing the Brick Red and Eosine Pink combination" },
  110: { pair: "/looks/plate-110.jpg", alt: "Two models wearing the Vandyke Brown and Brown combination" },
  111: { pair: "/looks/plate-111.jpg", alt: "Two models wearing the Yellow Green and Pale Lemon Yellow combination" },
  112: { pair: "/looks/plate-112.jpg", alt: "Two models wearing the Black and Grenadine Pink combination" },
  113: { pair: "/looks/plate-113.jpg", alt: "Two models wearing the Vandyke Brown and Seashell Pink combination" },
  114: { pair: "/looks/plate-114.jpg", alt: "Two models wearing the Antwarp Blue and Orange Yellow combination" },
  115: { pair: "/looks/plate-115.jpg", alt: "Two models wearing the Peach Red and Naples Yellow combination" },
  116: { pair: "/looks/plate-116.jpg", alt: "Two models wearing the Blue Violet and Cameo Pink combination" },
  117: { pair: "/looks/plate-117.jpg", alt: "Two models wearing the Black and Carmine combination" },
  118: { pair: "/looks/plate-118.jpg", alt: "Two models wearing the Vandyke Brown and Yellow Ocher combination" },
  119: { pair: "/looks/plate-119.jpg", alt: "Two models wearing the Dark Tyrian Blue and Light Glaucous Blue combination" },
  120: { pair: "/looks/plate-120.jpg", alt: "Two models wearing the Pompeian Red and Cameo Pink combination" },
  121: { pair: "/looks/plate-121.jpg", alt: "Two models wearing the Lincoln Green, Ochraceous Salmon, and Brown combination" },
  122: { pair: "/looks/plate-122.jpg", alt: "Two models wearing the Benzol Green, Cream Yellow, and Carmine combination" },
  123: { pair: "/looks/plate-123.jpg", alt: "Two models wearing the Taupe Brown, Coral Red, and Lemon Yellow combination" },
  124: { pair: "/looks/plate-124.jpg", alt: "Two models wearing the Pale Burnt Lake, Olive Yellow, and Yellow Ocher combination" },
  125: { pair: "/looks/plate-125.jpg", alt: "Two models wearing the Violet Blue, Fawn, and Cerulian Blue combination" },
  126: { pair: "/looks/plate-126.jpg", alt: "Two models wearing the Deep Lyons Blue, Ivory Buff, and Yellow Ocher combination" },
  127: { pair: "/looks/plate-127.jpg", alt: "Two models wearing the Dark Soft Violet, Pistachio Green, and Cinnamon Buff combination" },
  128: { pair: "/looks/plate-128.jpg", alt: "Two models wearing the Venice Green, Corinthian Pink, and Light Mauve combination" },
  129: { pair: "/looks/plate-129.jpg", alt: "Two models wearing the Khaki, Salvia Blue, and Apricot Yellow combination" },
  130: { pair: "/looks/plate-130.jpg", alt: "Two models wearing the Violet, Carmine Red, and Raw Sienna combination" },
  131: { pair: "/looks/plate-131.jpg", alt: "Two models wearing the Peacock Blue, Raw Sienna, and English Red combination" },
  132: { pair: "/looks/plate-132.jpg", alt: "Two models wearing the Citrine, Sulpher Yellow, and Golden Yellow combination" },
  133: { pair: "/looks/plate-133.jpg", alt: "Two models wearing the Vandyke Red, Sea Green, and Citrine combination" },
  134: { pair: "/looks/plate-134.jpg", alt: "Two models wearing the Red Violet, Light Mauve, and Eosine Pink combination" },
  135: { pair: "/looks/plate-135.jpg", alt: "Two models wearing the Salvia Blue, Sulpher Yellow, and Cossack Green combination" },
  136: { pair: "/looks/plate-136.jpg", alt: "Two models wearing the Red Violet, Dull Viridian Green, and Scarlet combination" },
  137: { pair: "/looks/plate-137.jpg", alt: "Two models wearing the Pistachio Green, Cinnamon Buff, and Etruscan Red combination" },
  138: { pair: "/looks/plate-138.jpg", alt: "Two models wearing the Venice Green, Golden Yellow, and Lemon Yellow combination" },
  139: { pair: "/looks/plate-139.jpg", alt: "Two models wearing the Salvia Blue, Neutral Gray, and Deep Indigo combination" },
  140: { pair: "/looks/plate-140.jpg", alt: "Two models wearing the Slate Color, Antwarp Blue, and Golden Yellow combination" },
};
