// Realistic editorial images can be added one palette at a time.
// Palettes without an entry continue to use the scalable SVG figures.
export const LOOKS = {
  1: {
    pair: "/looks/plate-001.jpg",
    alt: "Two models wearing the Cerulian Blue and English Red combination",
  },
  2: {
    pair: "/looks/plate-002.jpg",
    alt: "Two models wearing the Dark Tyrian Blue and Yellow Orange combination",
  },
  3: {
    pair: "/looks/plate-003.jpg",
    alt: "Two models wearing the Raw Sienna and Pale Lemon Yellow combination",
  },
  4: {
    pair: "/looks/plate-004.jpg",
    alt: "Two models wearing the Red Violet and Isabella Color combination",
  },
  5: {
    pair: "/looks/plate-005.jpg",
    alt: "Two models wearing the Vandar Poel's Blue and Cossack Green combination",
  },
  6: {
    pair: "/looks/plate-006.jpg",
    alt: "Two models wearing the Deep Indigo and Grenadine Pink combination",
  },
  7: {
    pair: "/looks/plate-007.jpg",
    alt: "Two models wearing the Orange and Glaucous Green combination",
  },
  8: {
    pair: "/looks/plate-008.jpg",
    alt: "Two models wearing the Cinnamon Rufous and Grayish Lavender combination",
  },
  9: {
    pair: "/looks/plate-009.jpg",
    alt: "Two models wearing the Violet Red and Dull Blue Violet combination",
  },
  10: {
    pair: "/looks/plate-010.jpg",
    alt: "Two models wearing the Dark Citrine and Cinnamon Rufous combination",
  },
  11: {
    pair: "/looks/plate-011.jpg",
    alt: "Two models wearing the Mineral Gray and Ivory Buff combination",
  },
  12: {
    pair: "/looks/plate-012.jpg",
    alt: "Two models wearing the Green Blue and Isabella Color combination",
  },
  13: {
    pair: "/looks/plate-013.jpg",
    alt: "Two models wearing the Veronia Purple and Raw Sienna combination",
  },
  14: {
    pair: "/looks/plate-014.jpg",
    alt: "Two models wearing the Spinel Red and Naples Yellow combination",
  },
  15: {
    pair: "/looks/plate-015.jpg",
    alt: "Two models wearing the Benzol Green and Grayish Lavender combination",
  },
  16: {
    pair: "/looks/plate-016.jpg",
    alt: "Two models wearing the Vandyke Red and Pale King's Blue combination",
  },
  17: {
    pair: "/looks/plate-017.jpg",
    alt: "Two models wearing the Eugenia Red and Sea Green combination",
  },
  18: {
    pair: "/looks/plate-018.jpg",
    alt: "Two models wearing the Dusky Madder Violet and Fawn combination",
  },
  19: {
    pair: "/looks/plate-019.jpg",
    alt: "Two models wearing the Mars Brown Tobacco and Night Green combination",
  },
  20: {
    pair: "/looks/plate-020.jpg",
    alt: "Two models wearing the Laelia Pink and Calamine Blue combination",
  },
  21: {
    pair: "/looks/plate-021.jpg",
    alt: "Two models wearing the Sea Green and Grenadine Pink combination",
  },
  22: {
    pair: "/looks/plate-022.jpg",
    alt: "Two models wearing the Deep Lyons Blue and Yellow combination",
  },
  23: {
    pair: "/looks/plate-023.jpg",
    alt: "Two models wearing the Light Mauve and Cinnamon Buff combination",
  },
  24: {
    pair: "/looks/plate-024.jpg",
    alt: "Two models wearing the Sepia and Veronia Purple combination",
  },
  25: { pair: "/looks/plate-025.jpg", alt: "Two models wearing the Etruscan Red and Nile Blue combination" },
  26: { pair: "/looks/plate-026.jpg", alt: "Two models wearing the Pale Raw Umber and Golden Yellow combination" },
  27: { pair: "/looks/plate-027.jpg", alt: "Two models wearing the Slate Color and Corinthian Pink combination" },
  28: { pair: "/looks/plate-028.jpg", alt: "Two models wearing the Deep Indigo and Madder Brown combination" },
  29: { pair: "/looks/plate-029.jpg", alt: "Two models wearing the Krongbergs Green and Salvia Blue combination" },
  30: { pair: "/looks/plate-030.jpg", alt: "Two models wearing the Pompeian Red and Mineral Gray combination" },
  31: {
    pair: "/looks/plate-031.jpg",
    alt: "Two models wearing the Red Orange and Pale Lemon Yellow combination",
  },
  32: {
    pair: "/looks/plate-032.jpg",
    alt: "Two models wearing the Ochraceous Salmon and Night Green combination",
  },
  33: { pair: "/looks/plate-033.jpg", alt: "Two models wearing the Slate Color and Raw Sienna combination" },
  34: { pair: "/looks/plate-034.jpg", alt: "Two models wearing the Eosine Pink and Neutral Gray combination" },
  35: { pair: "/looks/plate-035.jpg", alt: "Two models wearing the Carmine Red and Light Brown Drab combination" },
  36: {
    pair: "/looks/plate-036.jpg",
    alt: "Two models wearing the Sulphine Yellow and Turquoise Green combination",
  },
  37: { pair: "/looks/plate-037.jpg", alt: "Two models wearing the Red Violet and Brick Red combination" },
  38: { pair: "/looks/plate-038.jpg", alt: "Two models wearing the Deep Lyons Blue and Diamine Green combination" },
  39: { pair: "/looks/plate-039.jpg", alt: "Two models wearing the Helvetia Blue and Carmine combination" },
  40: {
    pair: "/looks/plate-040.jpg",
    variants: [
      "/looks/plate-040.jpg",
      "/looks/plate-040-v2.jpg",
      "/looks/plate-040-v3.jpg",
    ],
    alt: "Two models wearing the Vinaceous Tawny and Citron Yellow combination",
  },
  41: { pair: "/looks/plate-041.jpg", alt: "Two models wearing the Dark Citrine and Calamine Blue combination" },
  42: { pair: "/looks/plate-042.jpg", alt: "Two models wearing the Violet and Yellow Ocher combination" },
  43: { pair: "/looks/plate-043.jpg", alt: "Two models wearing the Aconite Violet and Corinthian Pink combination" },
  44: { pair: "/looks/plate-044.jpg", alt: "Two models wearing the Olympic Blue and Light Porcelain Green combination" },
  45: {
    pair: "/looks/plate-045.jpg",
    variants: [
      "/looks/plate-045.jpg",
      "/looks/plate-045-v2.jpg",
      "/looks/plate-045-v3.jpg",
    ],
    alt: "Two models wearing the Seashell Pink and Lemon Yellow combination",
  },
  46: { pair: "/looks/plate-046.jpg", alt: "Two models wearing the Black and Orange combination" },
  47: { pair: "/looks/plate-047.jpg", alt: "Two models wearing the Etruscan Red and Grayish Lavender B combination" },
  48: { pair: "/looks/plate-048.jpg", alt: "Two models wearing the Helvetia Blue and Rosolanc Purple combination" },
  49: { pair: "/looks/plate-049.jpg", alt: "Two models wearing the Blue and Pale King's Blue combination" },
  50: { pair: "/looks/plate-050.jpg", alt: "Two models wearing the Dusky Madder Violet and Ivory Buff combination" },
  51: { pair: "/looks/plate-051.jpg", alt: "Two models wearing the Carmine Red and Blue combination" },
  52: { pair: "/looks/plate-052.jpg", alt: "Two models wearing the Black and Sulpher Yellow combination" },
  53: { pair: "/looks/plate-053.jpg", alt: "Two models wearing the Dusky Madder Violet and Yellow Orange combination" },
  54: { pair: "/looks/plate-054.jpg", alt: "Two models wearing the Benzol Green and Light Glaucous Blue combination" },
  55: { pair: "/looks/plate-055.jpg", alt: "Two models wearing the Old Rose and White combination" },
  56: { pair: "/looks/plate-056.jpg", alt: "Two models wearing the Violet and Grayish Lavender B combination" },
  57: { pair: "/looks/plate-057.jpg", alt: "Two models wearing the Slate Color and Taupe Brown combination" },
  58: { pair: "/looks/plate-058.jpg", alt: "Two models wearing the Hay's Russet and Sea Green combination" },
  60: { pair: "/looks/plate-060.jpg", alt: "Two models wearing the Dark Tyrian Blue and Pale Lemon Yellow combination" },
  61: { pair: "/looks/plate-061.jpg", alt: "Two models wearing the Cotinga Purple and Light Green Yellow combination" },
  62: { pair: "/looks/plate-062.jpg", alt: "Two models wearing the Black and Yellow combination" },
  63: { pair: "/looks/plate-063.jpg", alt: "Two models wearing the Vistoris Lake and Cerulian Blue combination" },
  64: { pair: "/looks/plate-064.jpg", alt: "Two models wearing the Dark Soft Violet and Aconite Violet combination" },
  67: { pair: "/looks/plate-067.jpg", alt: "Two models wearing the Dark Tyrian Blue and Olympic Blue combination" },
  69: { pair: "/looks/plate-069.jpg", alt: "Two models wearing the Black and Warm Gray combination" },
  70: { pair: "/looks/plate-070.jpg", alt: "Two models wearing the Lincoln Green and Raw Sienna combination" },
  71: { pair: "/looks/plate-071.jpg", alt: "Two models wearing the Pompeian Red and Ochraceous Salmon combination" },
  72: { pair: "/looks/plate-072.jpg", alt: "Two models wearing the Pale King's Blue and Sulpher Yellow combination" },
  73: { pair: "/looks/plate-073.jpg", alt: "Two models wearing the Pale Raw Umber and Rainette Green combination" },
  74: { pair: "/looks/plate-074.jpg", alt: "Two models wearing the Green Blue and Turquoise Green combination" },
  75: { pair: "/looks/plate-075.jpg", alt: "Two models wearing the Violet Blue and Pale King's Blue combination" },
  77: { pair: "/looks/plate-077.jpg", alt: "Two models wearing the Vandar Poel's Blue and Eugenia Red B combination" },
  78: { pair: "/looks/plate-078.jpg", alt: "Two models wearing the Venice Green and Pinkish Cinnamon combination" },
  79: { pair: "/looks/plate-079.jpg", alt: "Two models wearing the Madder Brown and Green Blue combination" },
  80: { pair: "/looks/plate-080.jpg", alt: "Two models wearing the Light Mauve and Sulpher Yellow combination" },
  82: { pair: "/looks/plate-082.jpg", alt: "Two models wearing the Dusky Madder Violet and Hay's Russet combination" },
  83: { pair: "/looks/plate-083.jpg", alt: "Two models wearing the Violet Blue and Olive Buff combination" },
  59: {
    pair: "/looks/plate-059.jpg",
    alt: "Two models wearing the Citrine and Eosine Pink combination",
  },
  65: {
    pair: "/looks/plate-065.jpg",
    alt: "Two models wearing the Sulphine Yellow and Calamine Blue combination",
  },
  66: {
    pair: "/looks/plate-066.jpg",
    alt: "Two models wearing the Olive Green and Olive Ocher combination",
  },
  68: {
    pair: "/looks/plate-068.jpg",
    alt: "Two models wearing the Light Brown Drab and Yellow combination",
  },
  76: {
    pair: "/looks/plate-076.jpg",
    alt: "Two models wearing the Warm Gray and Pale Lemon Yellow combination",
  },
  81: {
    pair: "/looks/plate-081.jpg",
    alt: "Two models wearing the Warm Gray and Golden Yellow combination",
  },
  86: {
    pair: "/looks/plate-086.jpg",
    alt: "Two models wearing the Raw Sienna and Sea Green combination",
  },
  87: {
    pair: "/looks/plate-087.jpg",
    alt: "Two models wearing the Citron Yellow and Corinthian Pink combination",
  },
  93: {
    pair: "/looks/plate-093.jpg",
    alt: "Two models wearing the Citrine and Light Glaucous Blue combination",
  },
  96: {
    pair: "/looks/plate-096.jpg",
    alt: "Two models wearing the Olive and Yellow Ocher combination",
  },
  97: {
    pair: "/looks/plate-097.jpg",
    alt: "Two models wearing the Etruscan Red and Corinthian Pink combination",
  },
  102: {
    pair: "/looks/plate-102.jpg",
    alt: "Two models wearing the Orange Rufous and Ivory Buff combination",
  },
  104: {
    pair: "/looks/plate-104.jpg",
    alt: "Two models wearing the Carmine Red and Sulpher Yellow combination",
  },
  107: {
    pair: "/looks/plate-107.jpg",
    alt: "Two models wearing the Light Grayish Olive and Apricot Yellow combination",
  },
  109: {
    pair: "/looks/plate-109.jpg",
    alt: "Two models wearing the Blackish Olive and Pale Lemon Yellow combination",
  },
  222: {
    pair: "/looks/plate-222.jpg",
    alt: "Two models wearing the Orange Rufous and Yellow Ocher combination",
  },
  84: { pair: "/looks/plate-084.jpg", alt: "Two models wearing the Deep Slate Green and Seashell Pink combination" },
  85: { pair: "/looks/plate-085.jpg", alt: "Two models wearing the Antwarp Blue and Vinaceous Tawny combination" },
  88: { pair: "/looks/plate-088.jpg", alt: "Two models wearing the Blue and Seashell Pink combination" },
  89: { pair: "/looks/plate-089.jpg", alt: "Two models wearing the Violet Blue and Yellow Orange combination" },
  90: { pair: "/looks/plate-090.jpg", alt: "Two models wearing the Aconite Violet and Eosine Pink combination" },
  91: { pair: "/looks/plate-091.jpg", alt: "Two models wearing the Vistoris Lake and Orange Rufous combination" },
  92: { pair: "/looks/plate-092.jpg", alt: "Two models wearing the Benzol Green and Coral Red combination" },
  94: { pair: "/looks/plate-094.jpg", alt: "Two models wearing the Dusky Green and Ivory Buff combination" },
  95: { pair: "/looks/plate-095.jpg", alt: "Two models wearing the Dull Violet Black and Hay's Russet combination" },
  98: { pair: "/looks/plate-098.jpg", alt: "Two models wearing the Madder Brown and Violet Blue combination" },
  99: { pair: "/looks/plate-099.jpg", alt: "Two models wearing the Cerulian Blue and Pale Lemon Yellow combination" },
  100: { pair: "/looks/plate-100.jpg", alt: "Two models wearing the Dull Blue Violet and Buffy Citrine combination" },
  101: { pair: "/looks/plate-101.jpg", alt: "Two models wearing the Deep Lyons Blue and Cameo Pink combination" },
  103: { pair: "/looks/plate-103.jpg", alt: "Two models wearing the Dusky Madder Violet and Cinnamon Rufous combination" },
  105: { pair: "/looks/plate-105.jpg", alt: "Two models wearing the Chromium Green and Cameo Pink combination" },
  106: { pair: "/looks/plate-106.jpg", alt: "Two models wearing the Dull Violet Black and Antwarp Blue combination" },
  108: { pair: "/looks/plate-108.jpg", alt: "Two models wearing the Brick Red and Eosine Pink combination" },
  110: { pair: "/looks/plate-110.jpg", alt: "Two models wearing the Vandyke Brown and Brown combination" },
  111: { pair: "/looks/plate-111.jpg", alt: "Two models wearing the Yellow Green and Pale Lemon Yellow combination" },
  112: { pair: "/looks/plate-112.jpg", alt: "Two models wearing the Black and Grenadine Pink combination" },
  113: { pair: "/looks/plate-113.jpg", alt: "Two models wearing the Vandyke Brown and Seashell Pink combination" },
  114: { pair: "/looks/plate-114.jpg", alt: "Two models wearing the Antwarp Blue and Orange Yellow combination" },
  115: { pair: "/looks/plate-115.jpg", alt: "Two models wearing the Peach Red and Naples Yellow combination" },
  116: { pair: "/looks/plate-116.jpg", alt: "Two models wearing the Blue Violet and Cameo Pink combination" },
  117: { pair: "/looks/plate-117.jpg", alt: "Two models wearing the Black and Carmine combination" },
  118: { pair: "/looks/plate-118.jpg", alt: "Two models wearing the Vandyke Brown and Yellow Ocher combination" },
  119: { pair: "/looks/plate-119.jpg", alt: "Two models wearing the Dark Tyrian Blue and Light Glaucous Blue combination" },
  120: { pair: "/looks/plate-120.jpg", alt: "Two models wearing the Pompeian Red and Cameo Pink combination" },
  121: { pair: "/looks/plate-121.jpg", alt: "Two models wearing the Lincoln Green, Ochraceous Salmon, and Brown combination" },
  122: { pair: "/looks/plate-122.jpg", alt: "Two models wearing the Benzol Green, Cream Yellow, and Carmine combination" },
  123: { pair: "/looks/plate-123.jpg", alt: "Two models wearing the Taupe Brown, Coral Red, and Lemon Yellow combination" },
  124: { pair: "/looks/plate-124.jpg", alt: "Two models wearing the Pale Burnt Lake, Olive Yellow, and Yellow Ocher combination" },
  125: { pair: "/looks/plate-125.jpg", alt: "Two models wearing the Violet Blue, Fawn, and Cerulian Blue combination" },
  126: { pair: "/looks/plate-126.jpg", alt: "Two models wearing the Deep Lyons Blue, Ivory Buff, and Yellow Ocher combination" },
  127: { pair: "/looks/plate-127.jpg", alt: "Two models wearing the Dark Soft Violet, Pistachio Green, and Cinnamon Buff combination" },
  128: { pair: "/looks/plate-128.jpg", alt: "Two models wearing the Venice Green, Corinthian Pink, and Light Mauve combination" },
  129: { pair: "/looks/plate-129.jpg", alt: "Two models wearing the Khaki, Salvia Blue, and Apricot Yellow combination" },
  130: { pair: "/looks/plate-130.jpg", alt: "Two models wearing the Violet, Carmine Red, and Raw Sienna combination" },
  131: { pair: "/looks/plate-131.jpg", alt: "Two models wearing the Peacock Blue, Raw Sienna, and English Red combination" },
  132: { pair: "/looks/plate-132.jpg", alt: "Two models wearing the Citrine, Sulpher Yellow, and Golden Yellow combination" },
  133: { pair: "/looks/plate-133.jpg", alt: "Two models wearing the Vandyke Red, Sea Green, and Citrine combination" },
  134: { pair: "/looks/plate-134.jpg", alt: "Two models wearing the Red Violet, Light Mauve, and Eosine Pink combination" },
  135: { pair: "/looks/plate-135.jpg", alt: "Two models wearing the Salvia Blue, Sulpher Yellow, and Cossack Green combination" },
  136: { pair: "/looks/plate-136.jpg", alt: "Two models wearing the Red Violet, Dull Viridian Green, and Scarlet combination" },
  137: { pair: "/looks/plate-137.jpg", alt: "Two models wearing the Pistachio Green, Cinnamon Buff, and Etruscan Red combination" },
  138: { pair: "/looks/plate-138.jpg", alt: "Two models wearing the Venice Green, Golden Yellow, and Lemon Yellow combination" },
  139: { pair: "/looks/plate-139.jpg", alt: "Two models wearing the Salvia Blue, Neutral Gray, and Deep Indigo combination" },
  140: { pair: "/looks/plate-140.jpg", alt: "Two models wearing the Slate Color, Antwarp Blue, and Golden Yellow combination" },
  141: { pair: "/looks/plate-141.jpg", alt: "Two models wearing the Dark Tyrian Blue, Yellow Green, and Orange combination" },
  142: { pair: "/looks/plate-142.jpg", alt: "Two models wearing the Hydrangea Red, Salvia Blue, and Sulphine Yellow combination" },
  143: { pair: "/looks/plate-143.jpg", alt: "Two models wearing the Lilac, Warm Gray, and Blue combination" },
  144: { pair: "/looks/plate-144.jpg", alt: "Two models wearing the Black, Rosolanc Purple, and Orange combination" },
  145: { pair: "/looks/plate-145.jpg", alt: "Two models wearing the Dull Violet Black, Brown, and Citron Yellow combination" },
  146: { pair: "/looks/plate-146.jpg", alt: "Two models wearing the Deep Grayish Olive, Diamine Green, and Khaki combination" },
  147: { pair: "/looks/plate-147.jpg", alt: "Two models wearing the Vandyke Red, Turquoise Green, and Spinel Red combination" },
  148: { pair: "/looks/plate-148.jpg", alt: "Two models wearing the Cerulian Blue, Olive Ocher, and Orange Yellow combination" },
  149: { pair: "/looks/plate-149.jpg", alt: "Two models wearing the Deep Slate Green, Olive Ocher, and Orange combination" },
  150: { pair: "/looks/plate-150.jpg", alt: "Two models wearing the Glaucous Green, Seashell Pink, and Citron Yellow combination" },
  151: { pair: "/looks/plate-151.jpg", alt: "Two models wearing the Vandar Poel's Blue, Sulpher Yellow, and Yellow Orange combination" },
  152: { pair: "/looks/plate-152.jpg", alt: "Two models wearing the Hay's Russet, Light Glaucous Blue, and Etruscan Red combination" },
  153: { pair: "/looks/plate-153.jpg", alt: "Two models wearing the Eosine Pink, Citron Yellow, and Orange Yellow combination" },
  154: { pair: "/looks/plate-154.jpg", alt: "Two models wearing the Blue, Carmine, and Yellow combination" },
  155: { pair: "/looks/plate-155.jpg", alt: "Two models wearing the Deep Indigo, Benzol Green, and Jasper Red combination" },
  156: { pair: "/looks/plate-156.jpg", alt: "Two models wearing the Violet, Cobalt Green, and Olive Ocher combination" },
  157: { pair: "/looks/plate-157.jpg", alt: "Two models wearing the Pansy Purple, Olympic Blue, and Olive Ocher combination" },
  158: { pair: "/looks/plate-158.jpg", alt: "Two models wearing the Cinnamon Rufous, Night Green, and Lemon Yellow combination" },
  159: { pair: "/looks/plate-159.jpg", alt: "Two models wearing the Grayish Lavender - A, Calamine Blue, and Khaki combination" },
  160: { pair: "/looks/plate-160.jpg", alt: "Two models wearing the Pale Raw Umber, Dark Medici Blue, and Sulphine Yellow combination" },
  161: { pair: "/looks/plate-161.jpg", alt: "Two models wearing the Brown, Helvetia Blue, and Pinkish Cinnamon combination" },
  162: { pair: "/looks/plate-162.jpg", alt: "Two models wearing the Lilac, Rainette Green, and Old Rose combination" },
  163: { pair: "/looks/plate-163.jpg", alt: "Two models wearing the Antwarp Blue, Turquoise Green, and Apricot Yellow combination" },
  164: { pair: "/looks/plate-164.jpg", alt: "Two models wearing the Violet, Red Orange, and Orange Yellow combination" },
  165: { pair: "/looks/plate-165.jpg", alt: "Two models wearing the Vistoris Lake, Cameo Pink, and Spinel Red combination" },
  166: { pair: "/looks/plate-166.jpg", alt: "Two models wearing the Deep Slate Green, Naples Yellow, and Grenadine Pink combination" },
  167: { pair: "/looks/plate-167.jpg", alt: "Two models wearing the Ecru, Pale King's Blue, and Vandar Poel's Blue combination" },
  168: { pair: "/looks/plate-168.jpg", alt: "Two models wearing the Vandar Poel's Blue, Veronia Purple, and Lemon Yellow combination" },
  169: { pair: "/looks/plate-169.jpg", alt: "Two models wearing the Warm Gray, Corinthian Pink, and Pale Lemon Yellow combination" },
  170: { pair: "/looks/plate-170.jpg", alt: "Two models wearing the Red Violet, Rosolanc Purple, and Orange Yellow combination" },
  171: { pair: "/looks/plate-171.jpg", alt: "Two models wearing the Pale Burnt Lake, Glaucous Green, and Yellow Orange combination" },
  172: { pair: "/looks/plate-172.jpg", alt: "Two models wearing the Red Violet, Antwarp Blue, and Cinnamon Rufous combination" },
  173: { pair: "/looks/plate-173.jpg", alt: "Two models wearing the Madder Brown, Turquoise Green, and Lemon Yellow combination" },
  174: { pair: "/looks/plate-174.jpg", alt: "Two models wearing the Taupe Brown, Grayish Lavender - B, and Corinthian Pink combination" },
  175: { pair: "/looks/plate-175.jpg", alt: "Two models wearing the Pinkish Cinnamon, Olive Buff, and Blue Violet combination" },
  176: { pair: "/looks/plate-176.jpg", alt: "Two models wearing the Hermosa Pink, Seashell Pink, and Calamine Blue combination" },
  177: { pair: "/looks/plate-177.jpg", alt: "Two models wearing the Buffy Citrine, Grayish Lavender - A, and Pale Burnt Lake combination" },
  178: { pair: "/looks/plate-178.jpg", alt: "Two models wearing the Light Glaucous Blue, Ivory Buff, and Green Blue combination" },
  179: { pair: "/looks/plate-179.jpg", alt: "Two models wearing the Deep Lyons Blue, Golden Yellow, and Red Orange combination" },
  180: { pair: "/looks/plate-180.jpg", alt: "Two models wearing the Light Mauve, Neutral Gray, and Cinnamon Buff combination" },
  181: { pair: "/looks/plate-181.jpg", alt: "Two models wearing the Cotinga Purple, Violet, and Carmine Red combination" },
  182: { pair: "/looks/plate-182.jpg", alt: "Two models wearing the Deep Indigo, Vandyke Brown, and Raw Sienna combination" },
  183: { pair: "/looks/plate-183.jpg", alt: "Two models wearing the Veronia Purple, Deep Violet / Plumbeous, and Red Violet combination" },
  184: { pair: "/looks/plate-184.jpg", alt: "Two models wearing the Light Grayish Olive, Ivory Buff, and Spinel Red combination" },
  185: { pair: "/looks/plate-185.jpg", alt: "Two models wearing the Light Brown Drab, Pale Lemon Yellow, and Etruscan Red combination" },
  186: { pair: "/looks/plate-186.jpg", alt: "Two models wearing the Hay's Russet, Ochraceous Salmon, and Blue combination" },
  187: { pair: "/looks/plate-187.jpg", alt: "Two models wearing the Aconite Violet, Grayish Lavender - B, and Helvetia Blue combination" },
  188: { pair: "/looks/plate-188.jpg", alt: "Two models wearing the Rainette Green, Salvia Blue, and Cobalt Green combination" },
  189: { pair: "/looks/plate-189.jpg", alt: "Two models wearing the Deep Slate Olive, Venice Green, and Lemon Yellow combination" },
  190: { pair: "/looks/plate-190.jpg", alt: "Two models wearing the Black, Ivory Buff, and English Red combination" },
  191: { pair: "/looks/plate-191.jpg", alt: "Two models wearing the Blue, Light Brown Drab, and Yellow Ocher combination" },
  192: { pair: "/looks/plate-192.jpg", alt: "Two models wearing the Vandyke Brown, Deep Violet / Plumbeous, and Cream Yellow combination" },
  193: { pair: "/looks/plate-193.jpg", alt: "Two models wearing the Light Porcelain Green, Naples Yellow, and Grenadine Pink combination" },
  194: { pair: "/looks/plate-194.jpg", alt: "Two models wearing the Olympic Blue, Seashell Pink, and Jasper Red combination" },
  195: { pair: "/looks/plate-195.jpg", alt: "Two models wearing the Neutral Gray, Pale Lemon Yellow, and Spinel Red combination" },
  196: { pair: "/looks/plate-196.jpg", alt: "Two models wearing the Blue Violet, Pale King's Blue, and Citron Yellow combination" },
  197: { pair: "/looks/plate-197.jpg", alt: "Two models wearing the Dark Soft Violet, Neutral Gray, and Eosine Pink combination" },
  198: { pair: "/looks/plate-198.jpg", alt: "Two models wearing the Burnt Sienna, Green, and Apricot Yellow combination" },
  199: { pair: "/looks/plate-199.jpg", alt: "Two models wearing the Ochre Red, Light Brownish Olive, and Deep Lyons Blue combination" },
  200: { pair: "/looks/plate-200.jpg", alt: "Two models wearing the Chromium Green, Olive Buff, and Carmine Red combination" },
  201: { pair: "/looks/plate-201.jpg", alt: "Two models wearing the Olive, Cobalt Green, and Grenadine Pink combination" },
  202: { pair: "/looks/plate-202.jpg", alt: "Two models wearing the Slate Color, Turquoise Green, and Cobalt Green combination" },
  203: { pair: "/looks/plate-203.jpg", alt: "Two models wearing the Lincoln Green, Pale Lemon Yellow, and Vinaceous Cinnamon combination" },
  204: { pair: "/looks/plate-204.jpg", alt: "Two models wearing the Cinnamon Rufous, Light Glaucous Blue, and Rosolanc Purple combination" },
  205: { pair: "/looks/plate-205.jpg", alt: "Two models wearing the Violet, Vinaceous Cinnamon, and Pale Burnt Lake combination" },
  206: { pair: "/looks/plate-206.jpg", alt: "Two models wearing the Cinnamon Rufous, Corinthian Pink, and Golden Yellow combination" },
  207: { pair: "/looks/plate-207.jpg", alt: "Two models wearing the Black, Glaucous Green, and Sudan Brown combination" },
  208: { pair: "/looks/plate-208.jpg", alt: "Two models wearing the Green Blue, Sulpher Yellow, and Antwarp Blue combination" },
  209: { pair: "/looks/plate-209.jpg", alt: "Two models wearing the Salvia Blue, Ivory Buff, and Yellow Orange combination" },
  210: { pair: "/looks/plate-210.jpg", alt: "Two models wearing the Lincoln Green, Cinnamon Buff, and Lemon Yellow combination" },
  211: { pair: "/looks/plate-211.jpg", alt: "Two models wearing the Deep Indigo, Olive Yellow, and Apricot Orange combination" },
  212: { pair: "/looks/plate-212.jpg", alt: "Two models wearing the Orange Citrine, Salvia Blue, and Pompeian Red combination" },
  213: { pair: "/looks/plate-213.jpg", alt: "Two models wearing the Vinaceous Cinnamon, Pale King's Blue, and Apricot Yellow combination" },
  214: { pair: "/looks/plate-214.jpg", alt: "Two models wearing the Sudan Brown, Ivory Buff, and Violet combination" },
  215: { pair: "/looks/plate-215.jpg", alt: "Two models wearing the Blue, Eupatorium Purple, and Cream Yellow combination" },
  216: { pair: "/looks/plate-216.jpg", alt: "Two models wearing the Black, Green, and Jasper Red combination" },
  217: { pair: "/looks/plate-217.jpg", alt: "Two models wearing the Diamine Green, Ochraceous Salmon, and Pale Burnt Lake combination" },
  218: { pair: "/looks/plate-218.jpg", alt: "Two models wearing the Deep Violet / Plumbeous, Grayish Lavender - A, and Helvetia Blue combination" },
  219: { pair: "/looks/plate-219.jpg", alt: "Two models wearing the Dusky Green, Chromium Green, and Jasper Red combination" },
  220: { pair: "/looks/plate-220.jpg", alt: "Two models wearing the Aconite Violet, Ochraceous Salmon, and Pomegranite Purple combination" },
  221: { pair: "/looks/plate-221.jpg", alt: "Two models wearing the Black, Neutral Gray, and Carmine Red combination" },
  223: { pair: "/looks/plate-223.jpg", alt: "Two models wearing the Light Brown Drab, Turquoise Green, and Ochraceous Salmon combination" },
  224: { pair: "/looks/plate-224.jpg", alt: "Two models wearing the Taupe Brown, Dark Medici Blue, and Spinel Red combination" },
  225: { pair: "/looks/plate-225.jpg", alt: "Two models wearing the Dusky Green, Dark Slate Purple, and Carmine combination" },
  226: { pair: "/looks/plate-226.jpg", alt: "Two models wearing the Violet, Vistoris Lake, and Cream Yellow combination" },
  227: { pair: "/looks/plate-227.jpg", alt: "Two models wearing the Light Glaucous Blue, Hermosa Pink, and Cerulian Blue combination" },
  228: { pair: "/looks/plate-228.jpg", alt: "Two models wearing the Neutral Gray, Pale Lemon Yellow, and Carmine Red combination" },
  229: { pair: "/looks/plate-229.jpg", alt: "Two models wearing the Deep Slate Olive, Neutral Gray, and Golden Yellow combination" },
  230: { pair: "/looks/plate-230.jpg", alt: "Two models wearing the Cobalt Green, Turquoise Green, and Grenadine Pink combination" },
  231: { pair: "/looks/plate-231.jpg", alt: "Two models wearing the Olympic Blue, Cameo Pink, and Hay's Russet combination" },
  232: { pair: "/looks/plate-232.jpg", alt: "Two models wearing the Deep Indigo, Pinkish Cinnamon, and Carmine combination" },
  233: { pair: "/looks/plate-233.jpg", alt: "Two models wearing the Violet Blue, Buffy Citrine, and Carmine Red combination" },
  234: { pair: "/looks/plate-234.jpg", alt: "Two models wearing the Pale Raw Umber, Pale King's Blue, and Cinnamon Buff combination" },
  235: { pair: "/looks/plate-235.jpg", alt: "Two models wearing the Grayish Lavender - B, Ivory Buff, and Yellow Orange combination" },
  236: { pair: "/looks/plate-236.jpg", alt: "Two models wearing the Deep Lyons Blue, Purple Drab, and Khaki combination" },
  237: { pair: "/looks/plate-237.jpg", alt: "Two models wearing the Madder Brown, Salvia Blue, and Carmine Red combination" },
  238: { pair: "/looks/plate-238.jpg", alt: "Two models wearing the Warm Gray, Ochraceous Salmon, and Cotinga Purple combination" },
  239: { pair: "/looks/plate-239.jpg", alt: "Two models wearing the Light Brown Drab, Glaucous Green, and Pyrite Yellow combination" },
  240: { pair: "/looks/plate-240.jpg", alt: "Two models wearing the Cerulian Blue, Fresh Color, and Yellow combination" },
  241: { pair: "/looks/plate-241.jpg", alt: "Two models wearing the Dark Medici Blue, Pale Lemon Yellow, Isabella Color, and Red Orange combination" },
  242: { pair: "/looks/plate-242.jpg", alt: "Two models wearing the Black, Eosine Pink, Diamine Green, and Burnt Sienna combination" },
  243: { pair: "/looks/plate-243.jpg", alt: "Two models wearing the Slate Color, Ivory Buff, Kildare Green, and Raw Sienna combination" },
  244: { pair: "/looks/plate-244.jpg", alt: "Two models wearing the Andover Green, Light Brown Drab, Antwarp Blue, and Orange Rufous combination" },
  245: { pair: "/looks/plate-245.jpg", alt: "Two models wearing the Slate Color, Oil Green, Dark Tyrian Blue, and Carmine Red combination" },
  246: { pair: "/looks/plate-246.jpg", alt: "Two models wearing the Sulpher Yellow, Cinnamon Buff, Corinthian Pink, and Morocco Red combination" },
  247: { pair: "/looks/plate-247.jpg", alt: "Two models wearing the Deep Lyons Blue, Raw Sienna, Benzol Green, and Apricot Yellow combination" },
  248: { pair: "/looks/plate-248.jpg", alt: "Two models wearing the Grayish Lavender - A, Eosine Pink, Dark Slate Purple, and Khaki combination" },
  249: { pair: "/looks/plate-249.jpg", alt: "Two models wearing the Dark Medici Blue, Ecru, Hay's Russet, and Olive Ocher combination" },
  250: { pair: "/looks/plate-250.jpg", alt: "Two models wearing the Nile Blue, Pyrite Yellow, Sea Green, and Scarlet Orange combination" },
  251: { pair: "/looks/plate-251.jpg", alt: "Two models wearing the Slate Color, Diamine Green, Scarlet Red, and Yellow combination" },
  252: { pair: "/looks/plate-252.jpg", alt: "Two models wearing the Green Blue, Raw Sienna, Eugenia Red, and Sulphine Yellow combination" },
  253: { pair: "/looks/plate-253.jpg", alt: "Two models wearing the Slate Color, Apricot Orange, Cotinga Purple, and Lemon Yellow combination" },
  254: { pair: "/looks/plate-254.jpg", alt: "Two models wearing the Sulpher Yellow, Corinthian Pink, Mauve Taupe, and Olive combination" },
  255: { pair: "/looks/plate-255.jpg", alt: "Two models wearing the Black, Calamine Blue, Pyrite Yellow, and Raw Sienna combination" },
  256: { pair: "/looks/plate-256.jpg", alt: "Two models wearing the Black, Vinaceous Cinnamon, Dull Viridian Green, and Orange combination" },
  257: { pair: "/looks/plate-257.jpg", alt: "Two models wearing the Aconite Violet, Orange Yellow, Blue, and Scarlet combination" },
  258: { pair: "/looks/plate-258.jpg", alt: "Two models wearing the Pinkish Cinnamon, Olive, Antwarp Blue, and Pale Burnt Lake combination" },
  259: { pair: "/looks/plate-259.jpg", alt: "Two models wearing the Warm Gray, Green Blue, Helvetia Blue, and Lemon Yellow combination" },
  260: { pair: "/looks/plate-260.jpg", alt: "Two models wearing the Glaucous Green, Vinaceous Cinnamon, Old Rose, and Sea Green combination" },
  261: { pair: "/looks/plate-261.jpg", alt: "Two models wearing the Warm Gray, Pale Lemon Yellow, Calamine Blue, and Scarlet Red combination" },
  262: { pair: "/looks/plate-262.jpg", alt: "Two models wearing the Ivory Buff, Citrine, Cossack Green, and Eugenia Red combination" },
  263: { pair: "/looks/plate-263.jpg", alt: "Two models wearing the Slate Color, Turquoise Green, Pinkish Cinnamon, and Burnt Sienna combination" },
  264: { pair: "/looks/plate-264.jpg", alt: "Two models wearing the Dark Greenish Glaucous, Corinthian Pink, Cerulian Blue, and Red Orange combination" },
  265: { pair: "/looks/plate-265.jpg", alt: "Two models wearing the Dull Violet Black, Olive Yellow, Old Rose, and Apricot Yellow combination" },
  266: { pair: "/looks/plate-266.jpg", alt: "Two models wearing the Rainette Green, Ivory Buff, Benzol Green, and Scarlet combination" },
  267: { pair: "/looks/plate-267.jpg", alt: "Two models wearing the Blue, Cream Yellow, Benzol Green, and Yellow Orange combination" },
  268: { pair: "/looks/plate-268.jpg", alt: "Two models wearing the Deep Slate Olive, Nile Blue, Light Brown Drab, and Raw Sienna combination" },
  269: { pair: "/looks/plate-269.jpg", alt: "Two models wearing the Black, Aconite Violet, Pale Burnt Lake, and Raw Sienna combination" },
  270: { pair: "/looks/plate-270.jpg", alt: "Two models wearing the Sulpher Yellow, Olive Green, Cossack Green, and Eugenia Red combination" },
  271: { pair: "/looks/plate-271.jpg", alt: "Two models wearing the Deep Slate Green, Cobalt Green, Green Blue, and Pomegranite Purple combination" },
  272: { pair: "/looks/plate-272.jpg", alt: "Two models wearing the Salvia Blue, Pale Lemon Yellow, Turquoise Green, and Orange combination" },
  273: { pair: "/looks/plate-273.jpg", alt: "Two models wearing the Neutral Gray, Hermosa Pink, Sudan Brown, and Pansy Purple combination" },
  274: { pair: "/looks/plate-274.jpg", alt: "Two models wearing the Dark Citrine, Light Mauve, Olympic Blue, and Scarlet Orange combination" },
  275: { pair: "/looks/plate-275.jpg", alt: "Two models wearing the Ecru, Taupe Brown, Madder Brown, and Etruscan Red combination" },
  276: { pair: "/looks/plate-276.jpg", alt: "Two models wearing the Black, Seashell Pink, Eosine Pink, and Yellow Green combination" },
  277: { pair: "/looks/plate-277.jpg", alt: "Two models wearing the Dull Violet Black, Olive, Rosolanc Purple, and Spinel Red combination" },
  278: { pair: "/looks/plate-278.jpg", alt: "Two models wearing the Cossack Green, Cream Yellow, Dusky Green, and Olive Ocher combination" },
  279: { pair: "/looks/plate-279.jpg", alt: "Two models wearing the Ecru, Vinaceous Cinnamon, Dark Tyrian Blue, and Raw Sienna combination" },
  280: { pair: "/looks/plate-280.jpg", alt: "Two models wearing the Lincoln Green, Laelia Pink, Taupe Brown, and Eugenia Red combination" },
  281: { pair: "/looks/plate-281.jpg", alt: "Two models wearing the Cobalt Green, Pale Lemon Yellow, Antwarp Blue, and Benzol Green combination" },
  282: { pair: "/looks/plate-282.jpg", alt: "Two models wearing the Cobalt Green, Maple, Lilac, and Eugenia Red combination" },
  283: { pair: "/looks/plate-283.jpg", alt: "Two models wearing the Chromium Green, Venice Green, Ochre Red, and Pale Burnt Lake combination" },
  284: { pair: "/looks/plate-284.jpg", alt: "Two models wearing the Dusky Green, Sea Green, Peach Red, and Apricot Yellow combination" },
  285: { pair: "/looks/plate-285.jpg", alt: "Two models wearing the Light Brown Drab, Turquoise Green, Burnt Sienna, and Scarlet Orange combination" },
  286: { pair: "/looks/plate-286.jpg", alt: "Two models wearing the Violet Blue, Peacock Blue, Burnt Sienna, and Orange Yellow combination" },
  287: { pair: "/looks/plate-287.jpg", alt: "Two models wearing the Pale King's Blue, Calamine Blue, Eosine Pink, and Pyrite Yellow combination" },
  288: { pair: "/looks/plate-288.jpg", alt: "Two models wearing the Black, Taupe Brown, Sepia, and Yellow Orange combination" },
  289: { pair: "/looks/plate-289.jpg", alt: "Two models wearing the Violet Blue, Light Green Yellow, Dull Violet Black, and Lemon Yellow combination" },
  290: { pair: "/looks/plate-290.jpg", alt: "Two models wearing the Vistoris Lake, Cobalt Green, Lincoln Green, and Pale Lemon Yellow combination" },
  291: { pair: "/looks/plate-291.jpg", alt: "Two models wearing the Calamine Blue, Cobalt Green, Sea Green, and Light Green Yellow combination" },
  292: { pair: "/looks/plate-292.jpg", alt: "Two models wearing the Ecru, Pale Lemon Yellow, Isabella Color, and Pinkish Cinnamon combination" },
  293: { pair: "/looks/plate-293.jpg", alt: "Two models wearing the Artemesia Green, Turquoise Green, Green, and Raw Sienna combination" },
  294: { pair: "/looks/plate-294.jpg", alt: "Two models wearing the Salvia Blue, Sulpher Yellow, Cossack Green, and Cream Yellow combination" },
  295: { pair: "/looks/plate-295.jpg", alt: "Two models wearing the Dull Violet Black, Cream Yellow, Blue, and Yellow combination" },
  296: { pair: "/looks/plate-296.jpg", alt: "Two models wearing the Slate Color, Sulpher Yellow, Pale Raw Umber, and Ochraceous Salmon combination" },
  297: { pair: "/looks/plate-297.jpg", alt: "Two models wearing the Violet Blue, Burnt Sienna, Olive Green, and Yellow Orange combination" },
  298: { pair: "/looks/plate-298.jpg", alt: "Two models wearing the Black, Lemon Yellow, Raw Sienna, and Peach Red combination" },
  299: { pair: "/looks/plate-299.jpg", alt: "Two models wearing the Vinaceous Cinnamon, Oil Green, Antwarp Blue, and Indian Lake combination" },
  300: { pair: "/looks/plate-300.jpg", alt: "Two models wearing the Turquoise Green, Cream Yellow, Calamine Blue, and Grenadine Pink combination" },
  301: { pair: "/looks/plate-301.jpg", alt: "Two models wearing the Rainette Green, Ivory Buff, Aconite Violet, and Spectrum Red combination" },
  302: { pair: "/looks/plate-302.jpg", alt: "Two models wearing the Nile Blue, Ecru, Antwarp Blue, and Cream Yellow combination" },
  303: { pair: "/looks/plate-303.jpg", alt: "Two models wearing the Neutral Gray, Naples Yellow, Deep Slate Olive, and Peach Red combination" },
  304: { pair: "/looks/plate-304.jpg", alt: "Two models wearing the Dark Citrine, Cream Yellow, Hay's Russet, and Benzol Green combination" },
  305: { pair: "/looks/plate-305.jpg", alt: "Two models wearing the Turquoise Green, Pinkish Cinnamon, Citron Yellow, and Apricot Yellow combination" },
  306: { pair: "/looks/plate-306.jpg", alt: "Two models wearing the Nile Blue, Benzol Green, Dull Viridian Green, and Lemon Yellow combination" },
  307: { pair: "/looks/plate-307.jpg", alt: "Two models wearing the Grayish Lavender - A, Aconite Violet, Cotinga Purple, and Carmine combination" },
  308: { pair: "/looks/plate-308.jpg", alt: "Two models wearing the Fawn, Cobalt Green, Scarlet, and English Red combination" },
  309: { pair: "/looks/plate-309.jpg", alt: "Two models wearing the Violet Blue, Golden Yellow, Vandar Poel's Blue, and Apricot Orange combination" },
  310: { pair: "/looks/plate-310.jpg", alt: "Two models wearing the Deep Slate Olive, Sulpher Yellow, Pinkish Cinnamon, and Olive combination" },
  311: { pair: "/looks/plate-311.jpg", alt: "Two models wearing the Dark Greenish Glaucous, Cream Yellow, Pompeian Red, and Light Green Yellow combination" },
  312: { pair: "/looks/plate-312.jpg", alt: "Two models wearing the Artemesia Green, Burnt Sienna, Helvetia Blue, and Yellow Orange combination" },
  313: { pair: "/looks/plate-313.jpg", alt: "Two models wearing the Black, Carmine, Diamine Green, and Yellow combination" },
  314: { pair: "/looks/plate-314.jpg", alt: "Two models wearing the Dusky Madder Violet, Hay's Russet, Deep Lyons Blue, and Eosine Pink combination" },
  315: { pair: "/looks/plate-315.jpg", alt: "Two models wearing the Sulpher Yellow, Grenadine Pink, Eupatorium Purple, and Golden Yellow combination" },
  316: { pair: "/looks/plate-316.jpg", alt: "Two models wearing the Violet, Vandyke Red, Red Violet, and Dull Viridian Green combination" },
  317: { pair: "/looks/plate-317.jpg", alt: "Two models wearing the Ecru, Turquoise Green, Light Pinkish Cinnamon, and Lemon Yellow combination" },
  318: { pair: "/looks/plate-318.jpg", alt: "Two models wearing the Deep Slate Green, Light Brownish Olive, Blackish Olive, and Dusky Green combination" },
  319: { pair: "/looks/plate-319.jpg", alt: "Two models wearing the Cossack Green, Yellow Orange, Raw Sienna, and Apricot Yellow combination" },
  320: { pair: "/looks/plate-320.jpg", alt: "Two models wearing the Light Glaucous Blue, Sulpher Yellow, Coral Red, and Oil Green combination" },
  321: { pair: "/looks/plate-321.jpg", alt: "Two models wearing the Deep Slate Olive, Salvia Blue, Light Brown Drab, and Sulpher Yellow combination" },
  322: { pair: "/looks/plate-322.jpg", alt: "Two models wearing the Blue Violet, Eupatorium Purple, Brick Red, and Spectrum Red combination" },
  323: { pair: "/looks/plate-323.jpg", alt: "Two models wearing the Black, Cinnamon Buff, Madder Brown, and Citron Yellow combination" },
  324: { pair: "/looks/plate-324.jpg", alt: "Two models wearing the Neutral Gray, Olympic Blue, Aconite Violet, and Pompeian Red combination" },
  325: { pair: "/looks/plate-325.jpg", alt: "Two models wearing the Deep Slate Green, Naples Yellow, Eugenia Red B, and Yellow Ocher combination" },
  326: { pair: "/looks/plate-326.jpg", alt: "Two models wearing the Sulpher Yellow, Yellow Green, Night Green, and Peach Red combination" },
  327: { pair: "/looks/plate-327.jpg", alt: "Two models wearing the Grayish Lavender - B, Ecru, Eosine Pink, and Raw Sienna combination" },
  328: { pair: "/looks/plate-328.jpg", alt: "Two models wearing the Vandyke Brown, Light Porcelain Green, Brick Red, and Apricot Orange combination" },
  329: { pair: "/looks/plate-329.jpg", alt: "Two models wearing the Slate Color, Grayish Lavender - B, Cotinga Purple, and Cream Yellow combination" },
  330: { pair: "/looks/plate-330.jpg", alt: "Two models wearing the Nile Blue, Olive Buff, Salvia Blue, and Green Blue combination" },
  331: { pair: "/looks/plate-331.jpg", alt: "Two models wearing the Light Mauve, Violet, Dull Violet Black, and Indian Lake combination" },
  332: { pair: "/looks/plate-332.jpg", alt: "Two models wearing the Deep Slate Olive, Coral Red, Dusky Green, and Scarlet combination" },
  333: { pair: "/looks/plate-333.jpg", alt: "Two models wearing the Cobalt Green, Burnt Sienna, Blue, and Lemon Yellow combination" },
  334: { pair: "/looks/plate-334.jpg", alt: "Two models wearing the Seashell Pink, Olive, Antwarp Blue, and Yellow Green combination" },
  335: { pair: "/looks/plate-335.jpg", alt: "Two models wearing the Slate Color, Violet, Vandyke Red, and Yellow Orange combination" },
  336: { pair: "/looks/plate-336.jpg", alt: "Two models wearing the Blackish Olive, Pale Lemon Yellow, Hay's Russet, and Eosine Pink combination" },
  337: { pair: "/looks/plate-337.jpg", alt: "Two models wearing the Black, Laelia Pink, Vistoris Lake, and Violet Carmine combination" },
  338: { pair: "/looks/plate-338.jpg", alt: "Two models wearing the Grayish Lavender - B, Carmine Red, Dusky Green, and Orange Yellow combination" },
  339: { pair: "/looks/plate-339.jpg", alt: "Two models wearing the Light Glaucous Blue, Ochraceous Salmon, Violet Blue, and English Red combination" },
  340: { pair: "/looks/plate-340.jpg", alt: "Two models wearing the Black, Neutral Gray, Sea Green, and Peach Red combination" },
  341: { pair: "/looks/plate-341.jpg", alt: "Two models wearing the Deep Slate Olive, Light Glaucous Blue, Cossack Green, and Grenadine Pink combination" },
  342: { pair: "/looks/plate-342.jpg", alt: "Two models wearing the Deep Slate Olive, Corinthian Pink, Orange Citrine, and Cream Yellow combination" },
  343: { pair: "/looks/plate-343.jpg", alt: "Two models wearing the Deep Grayish Olive, Ivory Buff, Vandar Poel's Blue, and Burnt Sienna combination" },
  344: { pair: "/looks/plate-344.jpg", alt: "Two models wearing the Black, Aconite Violet, Deep Lyons Blue, and Cinnamon Buff combination" },
  345: { pair: "/looks/plate-345.jpg", alt: "Two models wearing the Nile Blue, Venice Green, Hay's Russet, and Blue Violet combination" },
  346: { pair: "/looks/plate-346.jpg", alt: "Two models wearing the Andover Green, Turquoise Green, Rosolanc Purple, and Light Green Yellow combination" },
  347: { pair: "/looks/plate-347.jpg", alt: "Two models wearing the Lilac, Olive Yellow, Helvetia Blue, and Sea Green combination" },
  348: { pair: "/looks/plate-348.jpg", alt: "Two models wearing the Deep Slate Olive, Olive Buff, Cossack Green, and Cotinga Purple combination" },
};
